<a href="https://colab.research.google.com/github/sandeep92134/PACKT-python-workshop/blob/main/module%2010/Exercise_131_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy has methods for creating matrices or n-dimensional arrays. One option is to place random numbers between 0 and 1 into each entry, as follows.

In this exercise, you will implement the various **numpy** matrix methods and observe the outputs (recall that **random.seed** will allow us to reproduce the same numbers, and it's okay if you want to generate your own).

The following steps will enable you to complete the exercise:

1. Begin with a new Jupyter Notebook.
2. Now, generate a random 5 x 5 matrix, as shown in the following code snippet:

 In the preceding code, you have used **random.seed**. You just invoke **random.seed(seed=60)**, and whenever you run the script, you will get the same sequence of values. This is very similar to the DataFrames that you will be dealing with for the rest of this book. You can go through some code to obtain particular rows, columns, and entries
3. Now, find the rows and columns of the matrix that is generated.
 
 In general, if you omit the columns from the matrix **[row, column]**, **numpy** will select them all.

 Note, you can equivalently write the preceding code as:

 Now, to find the values of all the rows, and the first column of the matrix.
4. Now find individual entries by specifying the value of the matrix **[row, column]**, as shown in the following code snippet: 
 
 Here is the **first** entry using another way:

 Entry in third row, fourth column:

 Now, to find the mean values of the matrix, you will find the mean of the entire matrix, individual rows, and columns using the **random_square.mean()** method, as shown in the following code snippet. Here is the **mean** entry of the matrix:

 Here is the **mean** entry of the first row:

 Here is the **mean** entry of the last column:

In [1]:
import numpy as np
np.random.seed(seed=60)
random_square = np.random.rand(5,5)
random_square

array([[0.30087333, 0.18694582, 0.32318268, 0.66574957, 0.5669708 ],
       [0.39825396, 0.37941492, 0.01058154, 0.1703656 , 0.12339337],
       [0.69240128, 0.87444156, 0.3373969 , 0.99245923, 0.13154007],
       [0.50032984, 0.28662051, 0.22058485, 0.50208555, 0.63606254],
       [0.63567694, 0.08043309, 0.58143375, 0.83919086, 0.29301825]])

In [2]:
# First row
random_square[0]

array([0.30087333, 0.18694582, 0.32318268, 0.66574957, 0.5669708 ])

In [3]:
# First row
random_square[0,:]

array([0.30087333, 0.18694582, 0.32318268, 0.66574957, 0.5669708 ])

In [4]:
# First column
random_square[:,0]

array([0.30087333, 0.39825396, 0.69240128, 0.50032984, 0.63567694])

In [5]:
# First entry
random_square[0,0]

0.30087333004661876

In [6]:
# First entry using another way
random_square[0][0]


0.30087333004661876

In [7]:
random_square[2,3]


0.9924592256795676

In [8]:
# Mean entry of matrix
random_square.mean()


0.42917627159618377

In [9]:
# Mean entry of first row
random_square[0].mean()

0.4087444389228477

In [10]:
# Mean entry of last column
random_square[:,-1].mean()

0.35019700684996913