<a href="https://colab.research.google.com/github/sandeep92134/PACKT-python-workshop/blob/main/module%209/Activity_23_Generating_a_List_of_Random_Numbers_in_a_Python_Virtual_Environment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Generating a List of Random Numbers in a Python Virtual Environment

You work for a sports betting website and want to simulate random events in a particular betting market. In order to do so, your goal will be to create a program that is able to generate long lists of random numbers using multiprocessing.

In this activity, the aim is to create a new Python environment, install the relevant packages, and write a function using the threading library to generate a list of random numbers.

Here are the steps:

1. Create a new **conda** environment called **my_env**.
2. Activate the **conda** environment.
3. Install **numpy** in your new environment.
4. Next, install and run a Jupyter notebook from within your virtual environment.
5. Next, create a new Jupyter notebook and **import** libraries such as **numpy**, **cProfile**, **itertools**, and **threading**.
6. Create a function that uses the **numpy** and **threading** libraries to generate an array of random numbers. Recall that when threading, we need to be able to send a signal for the **while** statement to terminate. The function should monitor the queue for an integer that represents the number of random numbers it should return. For example, if the number **10** was passed into the queue, it should return an array of **10** random numbers.
7. Next, add a function that will start a thread and put integers into the **in_queue** object. You can optionally print the output by setting the **show_output** argument to **True**. Make this function loop through the integers 0 to n, where n can be specified when the function is called. For each integer between **0** and **n**, it will pass the integer into the queue, and receive the array of random numbers.
8. Run the numbers on a small number of iterations to test.
9. Rerun the numbers with a large number of iterations and use **cProfile** to view a breakdown of what is taking time to execute.

In [1]:
import threading
import queue
import cProfile
import itertools
import numpy as np

np.random.seed(0)

In [2]:
in_queue = queue.Queue()
out_queue = queue.Queue()

def random_number_threading():
    while True:
        n = in_queue.get()
        if n == 'STOP':
            return
        random_numbers = np.random.rand(n)
        out_queue.put(random_numbers)


In [3]:
def generate_random_numbers(show_output, up_to):
    thread = threading.Thread(target=random_number_threading)
    thread.start()
    for i in range(up_to):
        in_queue.put(i)
        random_nums = out_queue.get()
        if show_output:
            print(random_nums)
    in_queue.put('STOP')
    thread.join()

In [4]:
generate_random_numbers(True, 10)

[]
[0.5488135]
[0.71518937 0.60276338]
[0.54488318 0.4236548  0.64589411]
[0.43758721 0.891773   0.96366276 0.38344152]
[0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
[0.0871293  0.0202184  0.83261985 0.77815675 0.87001215 0.97861834]
[0.79915856 0.46147936 0.78052918 0.11827443 0.63992102 0.14335329
 0.94466892]
[0.52184832 0.41466194 0.26455561 0.77423369 0.45615033 0.56843395
 0.0187898  0.6176355 ]
[0.61209572 0.616934   0.94374808 0.6818203  0.3595079  0.43703195
 0.6976312  0.06022547 0.66676672]


In [5]:
cProfile.run('generate_random_numbers(False, 20000)')

         740056 function calls in 4.049 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.066    0.066    4.048    4.048 <ipython-input-3-04f1b90debed>:1(generate_random_numbers)
        1    0.000    0.000    4.048    4.048 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 _weakrefset.py:38(_remove)
        1    0.000    0.000    0.000    0.000 _weakrefset.py:81(add)
    20001    0.076    0.000    0.335    0.000 queue.py:115(put)
    20000    0.112    0.000    3.647    0.000 queue.py:147(get)
    40000    0.025    0.000    0.035    0.000 queue.py:202(_qsize)
    20001    0.013    0.000    0.018    0.000 queue.py:206(_put)
    20000    0.012    0.000    0.017    0.000 queue.py:210(_get)
        1    0.000    0.000    0.000    0.000 threading.py:1024(join)
        1    0.000    0.000    0.000    0.000 threading.py:1062(_wait_for_tstate_lock)
        1    0.000    0.000    0.000    0.000 threadin